//component actions
const OPEN_SIDEBAR = "OPEN_SIDEBAR";
const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
const OPEN_THEME_CONTAINER = "OPEN_THEME_CONTAINER";
const CLOSE_THEME_CONTAINER = "CLOSE_THEME_CONTAINER";
const CHANGE_THEME = "CHANGE_THEME";
const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
const GET_PRODUTCS = 'GET_PRODUTCS';
const PRODUCTS_ERROR = 'PRODUCTS_ERROR';
const LOADING_SINGLE_PRODUCT = 'LOADING_SINGLE_PRODUCT';
const GET_SINGLE_PRODUCT ='GET_SINGLE_PRODUCT';
const SINGLE_PRODUCT_ERROR = 'SINGLE_PRODUCT_ERROR';
const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const CLEAR_CART = 'CLEAR_CART';
const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
const ENABLE_GRID_VIEW = 'ENABLE_GRID_VIEW';
const DISABLE_GRID_VIEW = 'DISABLE_GRID_VIEW';

//product actions

export {
  OPEN_SIDEBAR,
  CLOSE_SIDEBAR,
  OPEN_THEME_CONTAINER,
  CLOSE_THEME_CONTAINER,
  CHANGE_THEME,
  LOADING_PRODUCTS,
  GET_PRODUTCS,
  PRODUCTS_ERROR,
  LOADING_SINGLE_PRODUCT,
  GET_SINGLE_PRODUCT,
  SINGLE_PRODUCT_ERROR,
  ADD_TO_CART,
  REMOVE_FROM_CART,
  CLEAR_CART,
  LOAD_PRODUCTS,
  ENABLE_GRID_VIEW,
  DISABLE_GRID_VIEW
};
