//component actions
const OPEN_SIDEBAR = "OPEN_SIDEBAR";
const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
const OPEN_THEME_CONTAINER = "OPEN_THEME_CONTAINER";
const CLOSE_THEME_CONTAINER = "CLOSE_THEME_CONTAINER";
const TOGGLE_FILTERS = 'TOGGLE_FILTERS'
const CHANGE_THEME = "CHANGE_THEME";
const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
const GET_PRODUTCS = 'GET_PRODUTCS';
const PRODUCTS_ERROR = 'PRODUCTS_ERROR';
const LOADING_SINGLE_PRODUCT = 'LOADING_SINGLE_PRODUCT';
const GET_SINGLE_PRODUCT ='GET_SINGLE_PRODUCT';
const SINGLE_PRODUCT_ERROR = 'SINGLE_PRODUCT_ERROR';
const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
const ENABLE_GRID_VIEW = 'ENABLE_GRID_VIEW';
const DISABLE_GRID_VIEW = 'DISABLE_GRID_VIEW';
const SORT_PRODUCTS = 'SORT_PRODUCTS';
const UPDATE_SORT = 'UPDATE_SORT';
const CLEAR_FILTERS = 'CLEAR_FILTERS';
const UPDATE_FILTERS = 'UPDATE_FILTERS';
const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const CLEAR_CART = 'CLEAR_CART';
const CALCULATE_TOTALS = 'CALCULATE_TOTALS';
const UPDATE_AMOUNT = 'UPDATE_AMOUNT';
const OPEN_ADD_TO_CART = 'OPEN_ADD_TO_CART'
const CLOSE_ADD_TO_CART ='CLOSE_ADD_TO_CART';

//product actions

export {
  OPEN_SIDEBAR,
  CLOSE_SIDEBAR,
  OPEN_THEME_CONTAINER,
  CLOSE_THEME_CONTAINER,
  TOGGLE_FILTERS,
  CHANGE_THEME,
  LOADING_PRODUCTS,
  GET_PRODUTCS,
  PRODUCTS_ERROR,
  LOADING_SINGLE_PRODUCT,
  GET_SINGLE_PRODUCT,
  SINGLE_PRODUCT_ERROR,
  LOAD_PRODUCTS,
  ENABLE_GRID_VIEW,
  DISABLE_GRID_VIEW,
  SORT_PRODUCTS,
  UPDATE_SORT,
  CLEAR_FILTERS,
  UPDATE_FILTERS,
  FILTER_PRODUCTS,
  ADD_TO_CART,
  REMOVE_FROM_CART,
  CLEAR_CART,
  CALCULATE_TOTALS,
  UPDATE_AMOUNT, 
  OPEN_ADD_TO_CART,
  CLOSE_ADD_TO_CART
};
