//component actions
const OPEN_SIDEBAR = "OPEN_SIDEBAR";
const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
const OPEN_THEME_CONTAINER = "OPEN_THEME_CONTAINER";
const CLOSE_THEME_CONTAINER = "CLOSE_THEME_CONTAINER";
const CHANGE_THEME = "CHANGE_THEME";

//product actions

export {
  OPEN_SIDEBAR,
  CLOSE_SIDEBAR,
  OPEN_THEME_CONTAINER,
  CLOSE_THEME_CONTAINER,
  CHANGE_THEME,
};
